### ISSUE TITLE
Itineration plan v1.0 [DRAFT]

### ISSUE THREAD

**Issue by Acelator** [Acelator/Tasks-app#1]
This Iteration captures the work needed for the launch of the  v1.0 of the Tasks-app

<h2>Plan Items</h2>

Below is a summary of the top level plan items.

Legend of annotations:

| Mark | Description |
| ---------- | ---------- |
| :running_man: | work in progress |
| :hand: | blocked task |
| :muscle: |  stretch goal for this iteration |
| :red_circle: | missing issue reference |
|  :large_blue_circle: | more investigation required to remove uncertainty |

### Roadmap

- [ ] Publish the 2019 roadmap

### GUI

- [ ] Create all the views

### Server

- [ ] Improve server stability
- [ ] Use ErrorHandler

### Create Tasks

- [ ] Create unique Tasks_id for each board
- [ ] Add options to Archive Tasks

### Personalize Tasks

- [ ] Ability for change text colour
- [ ] If Possible support Markdown
- [ ] Add photos to the Tasks
- [ ] Create list on the Tasks
- [ ] Add time when create Task

### Login

- [ ] Add login functionality

### API

- [ ] Create API funcionality
- [ ] Launch beta version of the API

### Documentation

- [ ] Add complete documentation for the API

### Other

- [ ] Improve code quality
- [ ] Better in line comments
