### ISSUE TITLE
Iteration plan for V1.0 [DRAFT]

### ISSUE THREAD

**Issue by Acelator** [Acelator/Tasks-app#3]
This Iteration captures the work needed for the launch of the  v1.0 of the Tasks-app

<h2>Plan Items</h2>

Below is a summary of the top level plan items.

Legend of annotations:

| Mark | Description |
| ---------- | ---------- |
| :running_man: | work in progress |
| :hand: | blocked task |
| :muscle: |  stretch goal for this iteration |
| :red_circle: | missing issue reference |
|  :large_blue_circle: | more investigation required to remove uncertainty |

### Roadmap

- [ ] Publish the 2019 roadmap

### GUI

- [ ] Improve GUI

### Server

- [ ] Improve server stability
- [ ] Use ErrorHandler

### Models

- [ ] Join all the models in one file

### Create Boards and Tasks

- [ ] Create unique Board_Id for each boards 
- [ ] Create unique Tasks_id for each board
- [ ] Add options to Archive Boards and Tasks

### Login

- [ ] Add login funcionality

### API

- [ ] Create API funcionality
- [ ] Launch beta version of the API

### Documentation

- [ ] Add complete documentation for he API

### Other

- [ ] Improve code quality
- [ ] Better in line comments
